# ASSIGNMENT-1
WEB SCRAPING (Beautiful Soup)

# 1) Write a python program to display IMDB’s Top rated 100 Indian movies’ data
https://www.imdb.com/list/ls056092300/ (i.e. name, rating, year ofrelease) and make data frame.

In [1]:
!pip install bs4
!pip install requests

Collecting bs4
  Obtaining dependency information for bs4 from https://files.pythonhosted.org/packages/51/bb/bf7aab772a159614954d84aa832c129624ba6c32faa559dfb200a534e50b/bs4-0.0.2-py2.py3-none-any.whl.metadata
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.4)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2023.7.22)

In [2]:
from bs4 import BeautifulSoup
import requests

page=requests.get("https://www.imdb.com/list/ls056092300/")

In [4]:
soup=BeautifulSoup(page.content)

In [5]:
movie_name=[]

for i in soup.find_all('h3',class_="lister-item-header"):
      movie_name.append(i.text.replace("\n",''))
    
    
    
  
    
    
    
    
movie_name

['1.Ship of Theseus(2012)',
 '2.Iruvar(1997)',
 '3.Kaagaz Ke Phool(1959)',
 '4.Lagaan: Once Upon a Time in India(2001)',
 '5.Pather Panchali(1955)',
 '6.Charulata(1964)',
 '7.Rang De Basanti(2006)',
 '8.Dev.D(2009)',
 '9.3 Idiots(2009)',
 '10.Awaara(1951)',
 '11.Nayakan(1987)',
 '12.Aparajito(1956)',
 '13.Pushpaka Vimana(1987)',
 '14.Pyaasa(1957)',
 '15.Ghatashraddha(1977)',
 '16.Sholay(1975)',
 '17.Aradhana(1969)',
 '18.Do Ankhen Barah Haath(1957)',
 '19.Bombay(1995)',
 '20.Neecha Nagar(1946)',
 '21.Do Bigha Zamin(1953)',
 '22.Garm Hava(1974)',
 '23.Piravi(1989)',
 '24.Mughal-E-Azam(1960)',
 '25.Amma Ariyan(1986)',
 '26.Madhumati(1958)',
 '27.Goopy Gyne Bagha Byne(1969)',
 '28.Gangs of Wasseypur(2012)',
 '29.Guide(1965)',
 '30.Satya(1998)',
 '31.Roja(1992)',
 '32.Mr. India(1987)',
 '33.The Cloud-Capped Star(1960)',
 '34.Harishchandrachi Factory(2009)',
 '35.Masoom(1983)',
 '36.Agneepath(1990)',
 '37.Tabarana Kathe(1986)',
 '38.Zakhm(1998)',
 '39.Dil Chahta Hai(2001)',
 '40.Bhaag Milkha Bhaag(2013)',
 '41.Chupke Chupke(1975)',
 '42.Dilwale Dulhania Le Jayenge(1995)',
 '43.Taare Zameen Par(2007)',
 '44.Ardh Satya(1983)',
 '45.Bhumika(1977)',
 '46.Enthiran(2010)',
 '47.Sadma(1983)',
 '48.Shwaas(2004)',
 '49.Lamhe(1991)',
 '50.Haqeeqat(1964)',
 '51.Shree 420(1955)',
 '52.Kannathil Muthamittal(2002)',
 '53.Hum Aapke Hain Koun..!(1994)',
 '54.Ustad Hotel(2012)',
 '55.Bandit Queen(1994)',
 '56.Lakshya(2004)',
 '57.Black Friday(2004)',
 '58.Manthan(1976)',
 '59.Apoorva Raagangal(1975)',
 '60.English Vinglish(2012)',
 '61.Jewel Thief(1967)',
 '62.Pakeezah(1972)',
 '63.Maqbool(2003)',
 '64.Jis Desh Men Ganga Behti Hai(1960)',
 '65.Sahib Bibi Aur Ghulam(1962)',
 '66.Shatranj Ke Khilari(1977)',
 '67.Narthanasala(1963)',
 '68.Chandni Bar(2001)',
 '69.Vaaranam Aayiram(2008)',
 '70.Mr. and Mrs. Iyer(2002)',
 '71.Chandni(1989)',
 '72.English, August(1994)',
 '73.Celluloid(2013)',
 '74.Sagara Sangamam(1983)',
 '75.Munna Bhai M.B.B.S.(2003)',
 '76.Saaransh(1984)',
 '77.Guddi(1971)',
 '78.Vanaja(2006)',
 '79.Vazhakku Enn 18/9(2012)',
 '80.Gangaajal(2003)',
 '81.Angoor(1982)',
 '82.Guru(2007)',
 '83.Andaz Apna Apna(1994)',
 '84.Sangam(I) (1964)',
 '85.Oka Oori Katha(1978)',
 '86.Bhuvan Shome(1969)',
 '87.Border(I) (1997)',
 '88.Parineeta(2005)',
 '89.Devdas(1955)',
 '90.Abohomaan(2009)',
 '91.Kuch Kuch Hota Hai(1998)',
 '92.Pithamagan(2003)',
 '93.Veyyil(2006)',
 '94.Chemmeen(1965)',
 '95.Jaane Bhi Do Yaaro(1983)',
 '96.Apur Sansar(1959)',
 '97.Kanchivaram(2008)',
 '98.Monsoon Wedding(2001)',
 '99.Black(2005)',
 '100.Deewaar(1975)']

In [6]:
import re

def film_name(film):
    picture=[]
    for i in film:
        pattern=re.compile(r"\b[A-Za-z]+")
        find=re.findall(pattern,i)
        picture.append(find)
    return picture
    

title=film_name(movie_name)
title

[['Ship', 'of', 'Theseus'],
 ['Iruvar'],
 ['Kaagaz', 'Ke', 'Phool'],
 ['Lagaan', 'Once', 'Upon', 'a', 'Time', 'in', 'India'],
 ['Pather', 'Panchali'],
 ['Charulata'],
 ['Rang', 'De', 'Basanti'],
 ['Dev', 'D'],
 ['Idiots'],
 ['Awaara'],
 ['Nayakan'],
 ['Aparajito'],
 ['Pushpaka', 'Vimana'],
 ['Pyaasa'],
 ['Ghatashraddha'],
 ['Sholay'],
 ['Aradhana'],
 ['Do', 'Ankhen', 'Barah', 'Haath'],
 ['Bombay'],
 ['Neecha', 'Nagar'],
 ['Do', 'Bigha', 'Zamin'],
 ['Garm', 'Hava'],
 ['Piravi'],
 ['Mughal', 'E', 'Azam'],
 ['Amma', 'Ariyan'],
 ['Madhumati'],
 ['Goopy', 'Gyne', 'Bagha', 'Byne'],
 ['Gangs', 'of', 'Wasseypur'],
 ['Guide'],
 ['Satya'],
 ['Roja'],
 ['Mr', 'India'],
 ['The', 'Cloud', 'Capped', 'Star'],
 ['Harishchandrachi', 'Factory'],
 ['Masoom'],
 ['Agneepath'],
 ['Tabarana', 'Kathe'],
 ['Zakhm'],
 ['Dil', 'Chahta', 'Hai'],
 ['Bhaag', 'Milkha', 'Bhaag'],
 ['Chupke', 'Chupke'],
 ['Dilwale', 'Dulhania', 'Le', 'Jayenge'],
 ['Taare', 'Zameen', 'Par'],
 ['Ardh', 'Satya'],
 ['Bhumika'],
 ['Enthiran'],
 ['Sadma'],
 ['Shwaas'],
 ['Lamhe'],
 ['Haqeeqat'],
 ['Shree'],
 ['Kannathil', 'Muthamittal'],
 ['Hum', 'Aapke', 'Hain', 'Koun'],
 ['Ustad', 'Hotel'],
 ['Bandit', 'Queen'],
 ['Lakshya'],
 ['Black', 'Friday'],
 ['Manthan'],
 ['Apoorva', 'Raagangal'],
 ['English', 'Vinglish'],
 ['Jewel', 'Thief'],
 ['Pakeezah'],
 ['Maqbool'],
 ['Jis', 'Desh', 'Men', 'Ganga', 'Behti', 'Hai'],
 ['Sahib', 'Bibi', 'Aur', 'Ghulam'],
 ['Shatranj', 'Ke', 'Khilari'],
 ['Narthanasala'],
 ['Chandni', 'Bar'],
 ['Vaaranam', 'Aayiram'],
 ['Mr', 'and', 'Mrs', 'Iyer'],
 ['Chandni'],
 ['English', 'August'],
 ['Celluloid'],
 ['Sagara', 'Sangamam'],
 ['Munna', 'Bhai', 'M', 'B', 'B', 'S'],
 ['Saaransh'],
 ['Guddi'],
 ['Vanaja'],
 ['Vazhakku', 'Enn'],
 ['Gangaajal'],
 ['Angoor'],
 ['Guru'],
 ['Andaz', 'Apna', 'Apna'],
 ['Sangam', 'I'],
 ['Oka', 'Oori', 'Katha'],
 ['Bhuvan', 'Shome'],
 ['Border', 'I'],
 ['Parineeta'],
 ['Devdas'],
 ['Abohomaan'],
 ['Kuch', 'Kuch', 'Hota', 'Hai'],
 ['Pithamagan'],
 ['Veyyil'],
 ['Chemmeen'],
 ['Jaane', 'Bhi', 'Do', 'Yaaro'],
 ['Apur', 'Sansar'],
 ['Kanchivaram'],
 ['Monsoon', 'Wedding'],
 ['Black'],
 ['Deewaar']]

In [7]:
release_date=[]

for i in soup.find_all('span',class_="lister-item-year text-muted unbold"):
    release_date.append(i.text)
    
release_date

['(2012)',
 '(1997)',
 '(1959)',
 '(2001)',
 '(1955)',
 '(1964)',
 '(2006)',
 '(2009)',
 '(2009)',
 '(1951)',
 '(1987)',
 '(1956)',
 '(1987)',
 '(1957)',
 '(1977)',
 '(1975)',
 '(1969)',
 '(1957)',
 '(1995)',
 '(1946)',
 '(1953)',
 '(1974)',
 '(1989)',
 '(1960)',
 '(1986)',
 '(1958)',
 '(1969)',
 '(2012)',
 '(1965)',
 '(1998)',
 '(1992)',
 '(1987)',
 '(1960)',
 '(2009)',
 '(1983)',
 '(1990)',
 '(1986)',
 '(1998)',
 '(2001)',
 '(2013)',
 '(1975)',
 '(1995)',
 '(2007)',
 '(1983)',
 '(1977)',
 '(2010)',
 '(1983)',
 '(2004)',
 '(1991)',
 '(1964)',
 '(1955)',
 '(2002)',
 '(1994)',
 '(2012)',
 '(1994)',
 '(2004)',
 '(2004)',
 '(1976)',
 '(1975)',
 '(2012)',
 '(1967)',
 '(1972)',
 '(2003)',
 '(1960)',
 '(1962)',
 '(1977)',
 '(1963)',
 '(2001)',
 '(2008)',
 '(2002)',
 '(1989)',
 '(1994)',
 '(2013)',
 '(1983)',
 '(2003)',
 '(1984)',
 '(1971)',
 '(2006)',
 '(2012)',
 '(2003)',
 '(1982)',
 '(2007)',
 '(1994)',
 '(I) (1964)',
 '(1978)',
 '(1969)',
 '(I) (1997)',
 '(2005)',
 '(1955)',
 '(2009)',
 '(1998)',
 '(2003)',
 '(2006)',
 '(1965)',
 '(1983)',
 '(1959)',
 '(2008)',
 '(2001)',
 '(2005)',
 '(1975)']

In [8]:
ratings=[]


for i in soup.find_all('div',class_="ipl-rating-star small"):
    ratings.append(i.text.replace("\n",""))
    
ratings

['8',
 '8.4',
 '7.8',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '7.9',
 '8.4',
 '7.8',
 '8.6',
 '8.2',
 '8.6',
 '8.3',
 '7.6',
 '8.1',
 '7.6',
 '8.4',
 '8.1',
 '6.6',
 '8.3',
 '8',
 '7.8',
 '8.1',
 '7.4',
 '7.8',
 '8.7',
 '8.2',
 '8.3',
 '8.3',
 '8.1',
 '7.7',
 '7.8',
 '8.4',
 '8.4',
 '7.6',
 '8.1',
 '7.9',
 '8.1',
 '8.2',
 '8.3',
 '8',
 '8.3',
 '8.1',
 '7.4',
 '7.1',
 '8.3',
 '8.2',
 '7.2',
 '7.8',
 '7.9',
 '8.3',
 '7.5',
 '8.2',
 '7.5',
 '7.8',
 '8.4',
 '7.6',
 '7.6',
 '7.8',
 '7.9',
 '7.2',
 '8',
 '7.1',
 '8.1',
 '7.5',
 '8.1',
 '7.6',
 '8.2',
 '7.9',
 '6.7',
 '7.7',
 '7.7',
 '8.8',
 '8.1',
 '8.1',
 '7.2',
 '7.2',
 '8.3',
 '7.8',
 '8.3',
 '7.7',
 '8',
 '7.3',
 '7.8',
 '7.2',
 '7.9',
 '7.2',
 '7.7',
 '7.5',
 '7.5',
 '8.3',
 '7.9',
 '7.8',
 '8.3',
 '8.4',
 '8.2',
 '7.3',
 '8.1',
 '8']

In [9]:
print(len(movie_name),len(release_date),len(ratings))

100 100 100

In [10]:
import pandas as pd

df=pd.DataFrame({"Name":title,"Ratings":ratings,"Year_of_release":release_date})
df

                                        Name Ratings Year_of_release
0                        [Ship, of, Theseus]       8          (2012)
1                                   [Iruvar]     8.4          (1997)
2                        [Kaagaz, Ke, Phool]     7.8          (1959)
3   [Lagaan, Once, Upon, a, Time, in, India]     8.1          (2001)
4                         [Pather, Panchali]     8.2          (1955)
..                                       ...     ...             ...
95                            [Apur, Sansar]     8.4          (1959)
96                             [Kanchivaram]     8.2          (2008)
97                        [Monsoon, Wedding]     7.3          (2001)
98                                   [Black]     8.1          (2005)
99                                 [Deewaar]       8          (1975)

[100 rows x 3 columns]

# 2) Write a python program to scrape product name, price and discounts from
https://peachmode.com/search?q=bags

In [11]:
page1=requests.get("https://peachmode.com/search?q=bags")

In [12]:
soup1=BeautifulSoup(page1.content)

In [13]:
page1=requests.get("https://peachmode.com/search?q=bags")
page1

soup1=BeautifulSoup(page1.content)

product_name = []

for item in soup1.find_all('div', class_="st-product st-col-xs-6 st-col-sm-3 st-col-md-3"):
    product_name.append(item.text)

product_name

['\n\n\n\n\n\n\nSold Out\nSAVE ${item.discount}$%\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n${ item.title }$\n\n\n\n\nFrom \n${currency }$${ numberWithComa(item.activeDiscountedPrice) }$\n${ currency }$${numberWithComa(item.activePrice) }$\n\n\n\n\n${currency }$${ numberWithComa(item.activeDiscountedPrice) }$\n\n${getTotalQuantity(item.variants)}$ in Stock\n\n\n\n\n\n\n\n\n']

# 3) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

In [50]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
info=requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
soup=BeautifulSoup(info.content)
team=soup.find_all('tr',class_=('rankings-block__banner','table-body'))
top10=team[0:10]
data = {'Team_Name':[],'Matches': [],'Points': [],'Rating':[]}
for i in top10:
    pnt=i.find_all('td',recursive=True)
    data['Team_Name'].append(i.find('span',class_='u-hide-phablet').text)
    data['Matches'].append(pnt[2].text)
    data['Points'].append(pnt[3].text)
    data['Rating'].append(pnt[4].text.replace('\n',''))
MenTeam=pd.DataFrame(data,index=range(1,11))
MenTeam

ValueError: Length of values (0) does not match length of index (10)

In [53]:
# b) Top 10 ODI Batsmen along with the records of their team and rating.

In [51]:
req=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
soup=BeautifulSoup(req.content)
player=soup.find_all('tr',class_=('rankings-block__banner','table-body'))
top10=player[0:10]
data={'Player_Name':[],'Team_Name': [], 'Rating':[]}
for i in Top10:
    bat=i.find_all('td',recursive=True)
    data['Player_Name'].append(bat[1].text.replace('\n',''))
    data['Team_Name'].append(bat[2].text.replace('\n',''))
    data['Rating'].append(bat[3].text.replace('\n',''))
ODIBATSMAN=pd.DataFrame(data,index=range(1,11))
ODIBATSMAN

NameError: name 'Top10' is not defined

In [ ]:
# c) Top 10 ODI bowlers along with the records of their team and rating.

In [52]:
req=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
soup=BeautifulSoup(req.content)
bowler=soup.find_all('tr',class_=('rankings-block__banner','table-body'))
Top10=bowler[0:10]
bdata={'Player_Name':[],'Team_Name': [], 'Rating':[]}
for i in Top10:
    bat=i.find_all('td',recursive=True)
    bdata['Player_Name'].append(bat[1].text.replace('\n',''))
    bdata['Team_Name'].append(bat[2].text.replace('\n',''))
    bdata['Rating'].append(bat[3].text.replace('\n',''))
ODIBOWL=pd.DataFrame(bdata,index=range(1,11))
ODIBOWL

ValueError: Length of values (0) does not match length of index (10)

# 4) Write a python program to scrape details of all the posts from https://www.patreon.com/coreyms .Scrape the
heading, date, content and the likes for the video from the link for the youtube video from the post.

In [55]:
import requests
from bs4 import BeautifulSoup

patreon_url = "https://www.patreon.com/coreyms"
page = requests.get(patreon_url)
soup = BeautifulSoup(page.content, 'html.parser')

post_details = []
for post in soup.find_all('article'):
    heading = post.h2.text.strip()
    date = post.find('time', class_='entry-time').text.strip()
    content = post.find('div', class_='entry-content').text.strip()

In [56]:
video_container = soup.find('div', class_='video-container')
if video_container:
    youtube_video_url = video_container.find('iframe')['src']
    
else:
    youtube_video_url = None

In [57]:
import pandas as pd

# Create a DataFrame from the post_details list
columns = ['Heading', 'Date', 'Content', 'YouTube Video URL']
df = pd.DataFrame(post_details, columns=columns)

# Print the DataFrame or save it to a CSV file
print(df)

Empty DataFrame
Columns: [Heading, Date, Content, YouTube Video URL]
Index: []

# 5) Write a python program to scrape house details from mentioned URL. It should include house title, location,
area, EMI and price from https://www.nobroker.in/ .Enter three localities which are Indira Nagar, Jayanagar,
Rajaji Nagar

In [58]:
from bs4 import BeautifulSoup
import requests

page=requests.get("https://www.nobroker.in/property/sale/delhi/Indira%20Nagar,%20Adarsh%20Nagar?searchParam=W3sibGF0IjoyOC43MTczMDkxLCJsb24iOjc3LjE3MTM0MzEsInBsYWNlSWQiOiJDaElKa2ROcHNvd0JEVGtSRTQ0ZVNPbjlMY00iLCJwbGFjZU5hbWUiOiJJbmRpcmEgTmFnYXIsIEFkYXJzaCBOYWdhciJ9XQ==&radius=2.0&city=delhi&locality=Indira%20Nagar,%20Adarsh%20Nagar")
page
soup=BeautifulSoup(page.content)
title=[]

for i in soup.find_all('h2',class_="heading-6 flex items-center font-semi-bold m-0"):
    title.append(i.text)
    
title
location=[]

for i in soup.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
                       location.append(i.text)
                       
                       
location
area=[]

for i in soup.find_all('div',class_="flex flex-col w-33pe items-center tp:w-half po:w-full"):
    area.append(i.text.replace("sqftBuiltup","sqft"))
   
    
    
area
price=[]

for i in soup.find_all('div',class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"): 
     price.append(i.text.split("₹")[2])

        
        
price
emi=[]

for i in soup.find_all('div',class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"): 
     emi.append(i.text.split('₹')[4].replace("/MonthEstimated",""))

        
        
emi
import pandas as pd 

df=pd.DataFrame({"Title":title,"Location":location,"sqrt_area":area,"Rate":price,"EMI":emi})
df
from bs4 import BeautifulSoup
import requests

page=requests.get("https://www.nobroker.in/property/sale/bangalore/Rajajinagar?searchParam=W3sibGF0IjoxMi45OTgxNzMyLCJsb24iOjc3LjU1MzA0NDU5OTk5OTk5LCJwbGFjZUlkIjoiQ2hJSnhmVzREUE05cmpzUktzTlRHLTVwX1FRIiwicGxhY2VOYW1lIjoiUmFqYWppbmFnYXIifV0=&radius=2.0&city=bangalore&locality=Rajajinagar")
page

soup=BeautifulSoup(page.content)

title=[]

for i in soup.find_all('a',class_="overflow-hidden overflow-ellipsis whitespace-nowrap max-w-80pe po:max-w-full"):
    title.append(i.text)
    
title

location=[]

for i in soup.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
    location.append(i.text)
    
location

price=[]

for i in soup.find_all("div",class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    price.append(i.text.split("₹")[2])
    
price

emi=[]

for i in soup.find_all("div",class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    emi.append(i.text.split("₹")[4].replace("sqftBuiltup",""))
    
emi

area=[]

for i in soup.find_all("div",class_="flex flex-col w-33pe items-center tp:w-half po:w-full"):
    area.append(i.text.replace("sqftBuiltup",""))

    
area

import pandas as pd

df=pd.DataFrame({"Title":title,"Price":price,"Location":location,"area":area,"emi":emi})

df
from bs4 import BeautifulSoup
import requests

page=requests.get("https://www.nobroker.in/property/sale/bangalore/Jayanagar?searchParam=W3sibGF0IjoxMi45MzA3NzM1LCJsb24iOjc3LjU4MzgzMDIsInBsYWNlSWQiOiJDaElKMmRkbFo1Z1ZyanNSaDFCT0FhZi1vcnMiLCJwbGFjZU5hbWUiOiJKYXlhbmFnYXIiLCJzaG93TWFwIjpmYWxzZX1d&radius=2.0&city=bangalore&locality=Rajajinagar&isMetro=false")
page

soup=BeautifulSoup(page.content)

title=[]

for i in soup.find_all('a',class_="overflow-hidden overflow-ellipsis whitespace-nowrap max-w-80pe po:max-w-full"):
    title.append(i.text)
    
title

location=[]

for i in soup.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
    location.append(i.text)
    
location

price=[]

for i in soup.find_all("div",class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    price.append(i.text.split("₹")[2])
    
price

emi=[]

for i in soup.find_all("div",class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    emi.append(i.text.split("₹")[4].replace("sqftBuiltup",""))
    
emi

area=[]

for i in soup.find_all("div",class_="flex flex-col w-33pe items-center tp:w-half po:w-full"):
    area.append(i.text.replace("sqftBuiltup",""))

    
area

import pandas as pd

df=pd.DataFrame({"Title":title,"Price":price,"Location":location,"area":area,"emi":emi})

df

,Title,Price,Location,area,emi
0,3 BHK Apartment In Amarjyothi Apartments For S...,1.7 Crores,"Amarjyothi Apartments Jayanagar 6th block, Ba...","1,552","97,434/MonthEstimated EMI1,552"
1,2 BHK Apartment In Alpine Regency For Sale In...,1.65 Crores,"Alpine Regency Alpine Regency, 10th D Main R...","1,320","94,568/MonthEstimated EMI1,320"
2,4+ BHK House For Sale In Jayanagar,2.5 Crores,"Independent House, Tilak Nagar, near S.K. Bakery","2,500","1.43 Lacs/MonthEstimated EMI2,500"
3,3 BHK Flat In Santa Clara Apartment For Sale ...,1.15 Crores,"3Rd Cross Rd18th main, 9th Block, Marenahalli","1,395","65,911/MonthEstimated EMI1,395"
4,2 BHK Flat In Pallava Terrace Apartments For S...,1 Crore,17 north main yediyur behind samudaya bhavan b...,"1,050","57,314/MonthEstimated EMI1,050"
5,3 BHK House For Sale In Jayanagar 9th Block,1.45 Crores,"Independent House, 125a, 38th B Cross Road, ne...","1,400","83,106/MonthEstimated EMI1,400"
6,3 BHK Apartment In Lodha Azur For Sale near Ja...,2.25 Crores,"Lodha Azur Akshay Nagar,Bangalore","1,710","1.29 Lacs/MonthEstimated EMI1,710"
7,3 BHK Flat In Parasmani Regency For Sale In J...,2.77 Crores,behind Southend metro,"1,959","1.59 Lacs/MonthEstimated EMI1,959"
8,2 BHK Flat In Shanthi Park Apartments For Sale...,95 Lacs,"Shanthi Park Apartments, Kottapalya, Jayanagar...","1,100","54,448/MonthEstimated EMI1,100"
9,3 BHK House For Sale In Jayanagar,8.95 Crores,"Independent House, 9th Block,Near MEWA - VAN...","1,200","5.13 Lacs/MonthEstimated EMI1,200"
10,3 BHK Apartment In Jayanagar Residency For Sal...,2.25 Crores,Jayanagar Residency Jayanagar Jayanagar Resi...,"2,000","1.29 Lacs/MonthEstimated EMI2,000"
11,4+ BHK House For Sale In Jayanagar,7 Crores,"Independent House, No:1,First cross street,RBI...","4,000","4.01 Lacs/MonthEstimated EMI4,000"
12,2 BHK Flat In Jayanagar Residency For Sale In...,1.4 Crores,"jayanager residency. near D mart, Jayanager 3r...","1,167","80,240/MonthEstimated EMI1,167"
13,3 BHK Flat In Sri Maruthi For Sale In Jayanagar,1.2 Crores,Indira Gandhi Institute Of Child Health 1st Bl...,"1,400","68,777/MonthEstimated EMI1,400"
14,3 BHK Apartment In Gokul Lake View Apartments ...,1.7 Crores,Gokul Lake View Apartments Gokul Lake View Ap...,"1,852","97,434/MonthEstimated EMI1,852"
15,3 BHK Flat In Mayitri Enclave For Sale In Jay...,85 Lacs,"Mayitri Enclave,5T Block, 4th T Block East, Ja...","1,350","48,717/MonthEstimated EMI1,350"
16,4 BHK Apartment In B And B Opulent Spire For S...,5.19 Crores,B and B Opulent Spire Near Bharat Petroleum C...,"2,899","2.98 Lacs/MonthEstimated EMI2,899"
17,4+ BHK Flat In Gokula Krishna Apartment For Sa...,2.5 Crores,South End Rd near Reliance Fresh,"2,100","1.43 Lacs/MonthEstimated EMI2,100"
18,2 BHK Apartment In Chitramala Apartments For S...,70 Lacs,"Chitramala Apartments 4, Jaya Nagar 1st Block...",800,"40,120/MonthEstimated EMI800"
19,3 BHK Flat For Sale In Jayanagar,1.2 Crores,"Independent House, 11th main,Near Sri Raaghave...",450,"68,777/MonthEstimated EMI450"
20,4 BHK House For Sale In Margenhalli,85 Lacs,"Independent House, kanak pura road near Anjene...","2,000","48,717/MonthEstimated EMI2,000"
21,3 BHK House For Sale In Jayanagar,4.41 Crores,"Independent House, 28 main","1,350","2.52 Lacs/MonthEstimated EMI1,350"
22,3 BHK Flat In Omkar Sarovar Apartment For Sale...,1.4 Crores,sakamma garden,"1,450","80,240/MonthEstimated EMI1,450"
23,3 BHK Flat In Nisha Apartment For Sale In Ka...,80 Lacs,Jayanagar 3rd Block East near Medicure Hospit...,"1,300","45,851/MonthEstimated EMI1,300"
24,3 BHK Flat In Greenview Aparment For Sale In...,2.3 Crores,4th Block near Vivekananda Educational Centre,"2,114","1.32 Lacs/MonthEstimated EMI2,114"
25,3 BHK Apartment In Amarjyothi Apartments For S...,1.7 Crores,"Amarjyothi Apartments Jayanagar 6th block, Ba...","1,552","97,434/MonthEstimated EMI1,552"

# 6) Write a python program to scrape first 10 product details which include product name , price , Image URL from
https://www.bewakoof.com/bestseller?sort=popular .

In [59]:
from bs4 import BeautifulSoup
import requests
page=requests.get("https://www.bewakoof.com/bestseller?sort=popular")

soup=BeautifulSoup(page.content)

item_name=[]

for i in soup.find_all('h2',class_="clr-shade4 h3-p-name undefined false"):
    item_name.append(i.text)
    
item_name

["Women's Black Fragile Graphic Printed Boyfriend T-shirt",
 "Men's Blue Moon Knight Graphic Printed Oversized T-shirt",
 "Women's Pink & White Camo Printed Oversized Short Top",
 "Women's White Bored Typography Oversized Short Top",
 "Women's White & Black All Over Mickey Printed Oversized Short Top",
 "Women's Black All Over Printed Oversized Short Top",
 "Women's White All Over Tweety Printed Oversized Short Top",
 "Women's White All Over I Hate Mondays Printed Oversized Short Top",
 "Women's White Camo Printed Oversized Short Top",
 "Women's White MOTD Panda Graphic Printed T-shirt"]

In [60]:
rate=[]

for i in soup.find_all('div',class_="discountedPriceText clr-p-black false"):
    rate.append(i.text)
    
rate

['₹399',
 '₹469',
 '₹599',
 '₹549',
 '₹379',
 '₹399',
 '₹499',
 '₹379',
 '₹494',
 '₹369']

In [61]:
image_url=[]



for i in soup.find_all('div',class_="productCardImg false"):
    src=i.find('img')['src']
    image_url.append(src)
    
    
image_url

['https://images.bewakoof.com/t640/fragile-boyfriend-t-shirt-516553-1657179813-1.jpg',
 'https://images.bewakoof.com/t640/men-s-blue-moon-knight-graphic-printed-oversized-t-shirt-519226-1708697732-1.jpg',
 'https://images.bewakoof.com/t640/women-s-pink-white-camo-printed-oversized-t-shirt-580369-1686301190-1.jpg',
 'https://images.bewakoof.com/t640/women-white-printed-top-26-582038-1689082446-1.jpg',
 'https://images.bewakoof.com/t640/women-s-white-oversized-t-shirt-584434-1684230405-1.jpg',
 'https://images.bewakoof.com/t640/women-aop-oversize-t-shirt-3-580366-1682421809-1.JPG',
 'https://images.bewakoof.com/t640/women-aop-oversize-t-shirt-2-580367-1685446636-1.jpg',
 'https://images.bewakoof.com/t640/women-aop-oversized-t-shirt-11-582004-1685446587-1.jpg',
 'https://images.bewakoof.com/t640/women-aop-oversize-t-shirt-4-580364-1683887449-1.jpg',
 'https://images.bewakoof.com/t640/women-s-white-motd-panda-t-shirt-479771-1655815714-1.jpg']

In [62]:
print(len(item_name),len(rate),len(image_url))

10 10 10

In [63]:
import pandas as pd

df=pd.DataFrame({"Product_name":item_name,"Price":rate,"Image_url":image_url})
df

,Product_name,Price,Image_url
0,Women's Black Fragile Graphic Printed Boyfrien...,₹399,https://images.bewakoof.com/t640/fragile-boyfr...
1,Men's Blue Moon Knight Graphic Printed Oversiz...,₹469,https://images.bewakoof.com/t640/men-s-blue-mo...
2,Women's Pink & White Camo Printed Oversized Sh...,₹599,https://images.bewakoof.com/t640/women-s-pink-...
3,Women's White Bored Typography Oversized Short...,₹549,https://images.bewakoof.com/t640/women-white-p...
4,Women's White & Black All Over Mickey Printed ...,₹379,https://images.bewakoof.com/t640/women-s-white...
5,Women's Black All Over Printed Oversized Short...,₹399,https://images.bewakoof.com/t640/women-aop-ove...
6,Women's White All Over Tweety Printed Oversize...,₹499,https://images.bewakoof.com/t640/women-aop-ove...
7,Women's White All Over I Hate Mondays Printed ...,₹379,https://images.bewakoof.com/t640/women-aop-ove...
8,Women's White Camo Printed Oversized Short Top,₹494,https://images.bewakoof.com/t640/women-aop-ove...
9,Women's White MOTD Panda Graphic Printed T-shirt,₹369,https://images.bewakoof.com/t640/women-s-white...

# 7) Please visit https://www.cnbc.com/world/?region=world and scrapa) headings
b) date
c) News link

In [64]:
from bs4 import BeautifulSoup
import requests

page1=requests.get("https://www.cnbc.com/world/?region=world")

soup1=BeautifulSoup(page1.content)

headings=[]

for i in soup1.find_all('a',class_="LatestNews-headline"):
    headings.append(i.text)
    
headings

['How 26-year-old balances public office, working at Google and getting her MBA',
 "Here are the 3 key things we're most focused on in the stock market this week",
 "Pet insurance didn't feel worth it—until my cat needed a $3,000 surgery",
 'How this mission-driven chocolate company makes $162 million a year',
 'Nvidia CEO: Smart people struggle with these 2 traits—but they saved my company',
 "Generative AI 'FOMO' is driving tech heavyweights to invest billions in startups",
 'Decluttering tips from professional organizers that save time, money and stress',
 'As new vehicles become more like computers, what car shoppers need to know',
 'How Maersk grew its shipping empire and how it’s evolving',
 'Buy these 5 stocks with upside potential as April kicks off, Goldman Sachs says',
 'Crypto investors are bracing for a busy second quarter',
 'Watch out for these cyclical stocks, Morgan Stanley Investment Management says',
 "'Too few college-educated men': A look at why many women undergo egg freezing",
 'Monthly Meeting Q&A with Cramer: From energy to Costco to embracing sell-offs',
 "Trump's campaign trail promos for sneakers, bibles are unprecedented, experts say",
 'New report: The 10 richest retirement towns in the U.S.',
 'Just 1% of construction CEOs are women—how this 30-year-old became one of them',
 'Microsoft, Salesforce woo skeptical CFOs on new generative AI tool spending',
 'These were our 4 best — and 4 worst — portfolio stocks in the first quarter',
 "How a 36-year-old with 'little experience' built a $2 billion marketing company",
 '10 in-demand remote jobs paying over $100,000 that companies are hiring for now',
 'How to answer the updated crypto question when filing your taxes',
 '2 simple ways to get people to listen when you speak, says Stanford expert',
 'Key Fed inflation gauge rose 2.8% annually in February, as expected',
 'Tesla’s awful quarter has Wall Street on edge ahead of delivery numbers',
 "Watch CNBC's live coverage of Friday's key inflation data",
 "This sector should benefit from Fed rate cuts, says State Street's Bartolini",
 "Investors focused 'overwhelmingly' on bitcoin over other crypto, says BlackRock",
 'Morgan Stanley names its top picks for the catch-up trade in energy',
 'How long should you stay at your job? How to switch strategically']

In [65]:
time_str=[]

for i in soup1.find_all('time',class_="LatestNews-timestamp"):
    time_str.append(i.text)
    
time_str

news_link=[]

for i in soup1.find_all('a',class_="LatestNews-headline"):
    news_link.append(i['href'])
    
news_link

['https://www.cnbc.com/2024/03/30/meet-bushra-amiwala-one-of-the-first-gen-z-women-to-hold-public-office-in-the-us.html',
 'https://www.cnbc.com/2024/03/30/the-3-things-we-are-most-focused-on-in-the-stock-market-this-week.html',
 'https://www.cnbc.com/2024/03/30/is-pet-insurance-worth-it.html',
 'https://www.cnbc.com/2024/03/30/how-this-mission-driven-chocolate-company-makes-162-million-a-year.html',
 'https://www.cnbc.com/2024/03/30/nvidia-ceo-these-soft-skills-saved-my-2-trillion-company.html',
 'https://www.cnbc.com/2024/03/30/fomo-drives-tech-heavyweights-to-invest-billions-in-generative-ai-.html',
 'https://www.cnbc.com/2024/03/30/decluttering-tips-from-professional-organizers.html',
 'https://www.cnbc.com/2024/03/30/as-new-vehicles-become-more-like-computers-what-car-shoppers-need-to-know.html',
 'https://www.cnbc.com/2024/03/30/how-maersk-grew-its-shipping-empire-and-how-its-evolving.html',
 'https://www.cnbc.com/2024/03/30/goldman-sachs-says-buy-these-stocks-in-april.html',
 'https://www.cnbc.com/2024/03/30/crypto-investors-are-bracing-for-a-busy-quarter-with-the-bitcoin-halving-ether-etf-updates-and-potential-rate-cuts.html',
 'https://www.cnbc.com/2024/03/30/these-stocks-could-rally-in-second-phase-of-bull-market-morgan-stanley-investment-management-says.html',
 'https://www.cnbc.com/2024/03/30/a-look-at-why-many-women-undergo-egg-freezing-and-the-costs-associated-with-it.html',
 'https://www.cnbc.com/2024/03/29/monthly-meeting-qa-with-jim-cramer-everything-from-energy-to-costco-to-embracing-sell-offs.html',
 'https://www.cnbc.com/2024/03/29/trump-sellig-bibles-sneakers-perfume-on-campaign-trail-unprecedented-experts-say.html',
 'https://www.cnbc.com/2024/03/29/richest-retirement-towns-us-gobankingrates.html',
 'https://www.cnbc.com/2024/03/29/women-make-up-1percent-of-construction-ceoshow-this-30-year-old-became-one.html',
 'https://www.cnbc.com/2024/03/29/microsoft-salesforce-woo-skeptical-cfos-on-new-generative-ai-spending.html',
 'https://www.cnbc.com/2024/03/29/these-were-our-4-best-and-4-worst-portfolio-stocks-in-the-first-quarter.html',
 'https://www.cnbc.com/2024/03/29/ltk-founder-amber-venz-box-top-advice-for-inexperienced-entrepreneurs.html',
 'https://www.cnbc.com/2024/03/29/the-most-in-demand-remote-jobs-paying-over-100000-that-companies-are-hiring-for-right-now.html',
 'https://www.cnbc.com/2024/03/29/how-to-answer-updated-crypto-tax-question.html',
 'https://www.cnbc.com/2024/03/29/simple-ways-to-get-people-to-listen-when-you-speak-stanford-expert.html',
 'https://www.cnbc.com/2024/03/29/pce-inflation-report-february-2024-key-fed-inflation-gauge-rose-2point8percent-annually-as-expected.html',
 'https://www.cnbc.com/2024/03/29/tesla-stock-drops-29percent-in-first-quarter-as-global-dominance-wanes.html',
 'https://www.cnbc.com/2024/03/29/watch-cnbcs-live-coverage-of-fridays-key-inflation-data.html',
 'https://www.cnbc.com/2024/03/29/this-sector-notching-new-highs-should-benefit-from-fed-rate-cuts.html',
 'https://www.cnbc.com/2024/03/29/investors-focused-overwhelmingly-on-bitcoin-over-other-crypto-says-blackrock.html',
 'https://www.cnbc.com/2024/03/29/morgan-stanley-says-the-catch-up-trade-in-energy-can-continue-and-names-its-top-picks-to-play.html',
 'https://www.cnbc.com/2024/03/29/how-long-should-you-stay-at-your-job-how-to-switch-strategically.html']

In [66]:
print(len(headings),len(time_str),len(news_link))

30 30 30

In [67]:
from datetime import datetime,timedelta

time_frame=['7 Hours Ago',
 '11 Hours Ago',
 '11 Hours Ago',
 '11 Hours Ago',
 '11 Hours Ago',
 '12 Hours Ago',
 '12 Hours Ago',
 '12 Hours Ago',
 '13 Hours Ago',
 '14 Hours Ago',
 '15 Hours Ago',
 '15 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago',
 '18 Hours Ago']

def convert_time_date(timestring):
    hours_ago=int(timestring.split()[0])
    dt=datetime.now()-timedelta(hours=hours_ago)
    return dt.date()

date=[convert_time_date(timestring) for timestring in time_frame]

for dates in date:
    print(dates)

2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30
2024-03-30

In [68]:
df1=pd.DataFrame({"Headings":headings,"Date":date,"News_url":news_link})
df1

,Headings,Date,News_url
0,"How 26-year-old balances public office, workin...",2024-03-30,https://www.cnbc.com/2024/03/30/meet-bushra-am...
1,Here are the 3 key things we're most focused o...,2024-03-30,https://www.cnbc.com/2024/03/30/the-3-things-w...
2,Pet insurance didn't feel worth it—until my ca...,2024-03-30,https://www.cnbc.com/2024/03/30/is-pet-insuran...
3,How this mission-driven chocolate company make...,2024-03-30,https://www.cnbc.com/2024/03/30/how-this-missi...
4,Nvidia CEO: Smart people struggle with these 2...,2024-03-30,https://www.cnbc.com/2024/03/30/nvidia-ceo-the...
5,Generative AI 'FOMO' is driving tech heavyweig...,2024-03-30,https://www.cnbc.com/2024/03/30/fomo-drives-te...
6,Decluttering tips from professional organizers...,2024-03-30,https://www.cnbc.com/2024/03/30/decluttering-t...
7,"As new vehicles become more like computers, wh...",2024-03-30,https://www.cnbc.com/2024/03/30/as-new-vehicle...
8,How Maersk grew its shipping empire and how it...,2024-03-30,https://www.cnbc.com/2024/03/30/how-maersk-gre...
9,Buy these 5 stocks with upside potential as Ap...,2024-03-30,https://www.cnbc.com/2024/03/30/goldman-sachs-...
10,Crypto investors are bracing for a busy second...,2024-03-30,https://www.cnbc.com/2024/03/30/crypto-investo...
11,"Watch out for these cyclical stocks, Morgan St...",2024-03-30,https://www.cnbc.com/2024/03/30/these-stocks-c...
12,'Too few college-educated men': A look at why ...,2024-03-30,https://www.cnbc.com/2024/03/30/a-look-at-why-...
13,Monthly Meeting Q&A with Cramer: From energy t...,2024-03-30,https://www.cnbc.com/2024/03/29/monthly-meetin...
14,"Trump's campaign trail promos for sneakers, bi...",2024-03-30,https://www.cnbc.com/2024/03/29/trump-sellig-b...
15,New report: The 10 richest retirement towns in...,2024-03-30,https://www.cnbc.com/2024/03/29/richest-retire...
16,Just 1% of construction CEOs are women—how thi...,2024-03-30,https://www.cnbc.com/2024/03/29/women-make-up-...
17,"Microsoft, Salesforce woo skeptical CFOs on ne...",2024-03-30,https://www.cnbc.com/2024/03/29/microsoft-sale...
18,These were our 4 best — and 4 worst — portfoli...,2024-03-30,https://www.cnbc.com/2024/03/29/these-were-our...
19,How a 36-year-old with 'little experience' bui...,2024-03-30,https://www.cnbc.com/2024/03/29/ltk-founder-am...
20,"10 in-demand remote jobs paying over $100,000 ...",2024-03-30,https://www.cnbc.com/2024/03/29/the-most-in-de...
21,How to answer the updated crypto question when...,2024-03-30,https://www.cnbc.com/2024/03/29/how-to-answer-...
22,2 simple ways to get people to listen when you...,2024-03-30,https://www.cnbc.com/2024/03/29/simple-ways-to...
23,Key Fed inflation gauge rose 2.8% annually in ...,2024-03-30,https://www.cnbc.com/2024/03/29/pce-inflation-...
24,Tesla’s awful quarter has Wall Street on edge ...,2024-03-30,https://www.cnbc.com/2024/03/29/tesla-stock-dr...
25,Watch CNBC's live coverage of Friday's key inf...,2024-03-30,https://www.cnbc.com/2024/03/29/watch-cnbcs-li...
26,"This sector should benefit from Fed rate cuts,...",2024-03-30,https://www.cnbc.com/2024/03/29/this-sector-no...
27,Investors focused 'overwhelmingly' on bitcoin ...,2024-03-30,https://www.cnbc.com/2024/03/29/investors-focu...
28,Morgan Stanley names its top picks for the cat...,2024-03-30,https://www.cnbc.com/2024/03/29/morgan-stanley...
29,How long should you stay at your job? How to s...,2024-03-30,https://www.cnbc.com/2024/03/29/how-long-shoul...

# ) Please visit https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloadedarticles/ and scrap-
 a) Paper title
 b) date
 c) Author

In [69]:
from bs4 import BeautifulSoup
import requests

page2=requests.get("https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded-articles/")

page2

soup2=BeautifulSoup(page2.content)

paper_title=[]

    
for i in soup2.find_all('h2', class_="h5 article-title"):
    paper_title.append(i.text.replace('\n', '').replace('\r', ''))

paper_title

date=[]

for i in soup2.find_all('p',class_="article-date"):
    date.append(i.text)
    
date

author=[]

for i in soup2.find_all('p',class_="article-authors"):
    author.append(i.text)
    
author

[' Tanha Talaviya |  Dhara Shah |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah',
 ' Kirtan Jha |  Aalap Doshi |  Poojan Patel |  Manan Shah',
 ' Jinyuan Xu |  Baoxing Gu |  Guangzhao Tian',
 ' A. Subeesh |  C.R. Mehta',
 ' Zongmei Gao |  Yuanyuan Shao |  Guantao Xuan |  Yongxian Wang |  Yi Liu |  Xiang Han',
 ' Juzhong Tan |  Jie Xu',
 ' Matteo Rizzo |  Matteo Marcuzzo |  Alessandro Zangari |  Andrea Gasparetto |  Andrea Albarelli',
 ' Vijai Singh |  Namita Sharma |  Shikha Singh',
 ' V.G. Dhanya |  A. Subeesh |  N.L. Kushwaha |  Dinesh Kumar Vishwakarma |  T. Nagesh Kumar |  G. Ritika |  A.N. Singh',
 ' Md Taimur Ahad |  Yan Li |  Bo Song |  Touhid Bhuiyan',
 ' Ananda S. Paymode |  Vandana B. Malode',
 ' P. Isaac Ritharson |  Kumudha Raimond |  X. Anitha Mary |  Jennifer Eunice Robert |  Andrew J',
 ' Punam Bedi |  Pushkar Gole',
 ' Vilani Sachithra |  L.D.C.S. Subhashini',
 ' A. Subeesh |  S. Bhole |  K. Singh |  N.S. Chandel |  Y.A. Rajwade |  K.V.R. Rao |  S.P. Kumar |  D. Jat',
 ' Oumnia Ennaji |  Leonardus Vergütz |  Achraf El Allali',
 ' Filbert H. Juwono |  W.K. Wong |  Seema Verma |  Neha Shekhawat |  Basil Andy Lease |  Catur Apriono',
 ' Md Ekramul Hossain |  Muhammad Ashad Kabir |  Lihong Zheng |  Dave L. Swain |  Shawn McGrath |  Jonathan Medway',
 ' Abderahman Rejeb |  Karim Rejeb |  Suhaiza Zailani |  John G. Keogh |  Andrea Appolloni',
 ' Cedric Okinda |  Innocent Nyalala |  Tchalla Korohou |  Celestine Okinda |  Jintao Wang |  Tracy Achieng |  Patrick Wamalwa |  Tai Mang |  Mingxia Shen',
 ' Misbah Pathan |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah',
 ' Masahiro Ryo',
 ' Galib Muhammad Shahriar Himel |  Md. Masudul Islam |  Mijanur Rahaman',
 ' R. Abbasi |  P. Martinez |  R. Ahmad',
 ' Jie Xu |  Shuang Guo |  David Xie |  Yaxuan Yan']

In [70]:
    print(len(paper_title),len(date),len(author))

25 25 25

In [71]:
paper_title

['                    Implementation of artificial intelligence in agriculture for optimisation of irrigation and application of pesticides and herbicides                ',
 '                    A comprehensive review on automation in agriculture using artificial intelligence                ',
 '                    Review of agricultural IoT technology                ',
 '                    Automation and digitization of agriculture using artificial intelligence and internet of things                ',
 '                    Real-time hyperspectral imaging for the in-field estimation of strawberry ripeness with deep learning                ',
 '                    Applications of electronic nose (e-nose) and electronic tongue (e-tongue) in food quality-related properties determination: A review                ',
 '                    Fruit ripeness classification: A survey                ',
 '                    A review of imaging techniques for plant disease detection                ',
 '                    Deep learning based computer vision approaches for smart agricultural applications                ',
 '                    Comparison of CNN-based deep learning architectures for rice diseases classification                ',
 '                    Transfer Learning for Multi-Crop Leaf Disease Image Classification using Convolutional Neural Network VGG                ',
 '                    DeepRice: A deep learning and deep feature based classification of Rice leaf disease subtypes                ',
 '                    Plant disease detection using hybrid model based on convolutional autoencoder and convolutional neural network                ',
 '                    How artificial intelligence uses to achieve the agriculture sustainability: Systematic review                ',
 '                    Deep convolutional neural network models for weed detection in polyhouse grown bell peppers                ',
 '                    Machine learning in nutrient management: A review                ',
 '                    Machine learning for weed–plant discrimination in agriculture 5.0: An in-depth review                ',
 '                    A systematic review of machine learning techniques for cattle identification: Datasets, methods and future directions                ',
 '                    Examining the interplay between artificial intelligence and the agri-food industry                ',
 '                    A review on computer vision systems in monitoring of poultry: A welfare perspective                ',
 '                    Artificial cognition for applications in smart agriculture: A comprehensive review                ',
 '                    Explainable artificial intelligence and interpretable machine learning for agricultural data analysis                ',
 '                    Vision Intelligence for Smart Sheep Farming: Applying Ensemble Learning to Detect Sheep Breeds                ',
 '                    Crop diagnostic system: A robust disease detection and management system for leafy green crops grown in an aquaponics facility                ',
 '                    Blockchain: A new safeguard for agri-foods                ']

In [72]:
import pandas as pd

df2=pd.DataFrame({'Paper_title':paper_title,'Date':date,'Author':author})

df2

,Paper_title,Date,Author
0,Implementation of artifici...,2020,Tanha Talaviya | Dhara Shah | Nivedita Pate...
1,A comprehensive review on ...,June 2019,Kirtan Jha | Aalap Doshi | Poojan Patel | ...
2,Review of agricultural IoT...,2022,Jinyuan Xu | Baoxing Gu | Guangzhao Tian
3,Automation and digitizatio...,2021,A. Subeesh | C.R. Mehta
4,Real-time hyperspectral im...,2020,Zongmei Gao | Yuanyuan Shao | Guantao Xuan ...
5,Applications of electronic...,2020,Juzhong Tan | Jie Xu
6,Fruit ripeness classificat...,March 2023,Matteo Rizzo | Matteo Marcuzzo | Alessandro...
7,A review of imaging techni...,2020,Vijai Singh | Namita Sharma | Shikha Singh
8,Deep learning based comput...,2022,V.G. Dhanya | A. Subeesh | N.L. Kushwaha | ...
9,Comparison of CNN-based de...,September 2023,Md Taimur Ahad | Yan Li | Bo Song | Touhid...
10,Transfer Learning for Mult...,2022,Ananda S. Paymode | Vandana B. Malode
11,DeepRice: A deep learning ...,March 2024,P. Isaac Ritharson | Kumudha Raimond | X. A...
12,Plant disease detection us...,2021,Punam Bedi | Pushkar Gole
13,How artificial intelligenc...,June 2023,Vilani Sachithra | L.D.C.S. Subhashini
14,Deep convolutional neural ...,2022,A. Subeesh | S. Bhole | K. Singh | N.S. Ch...
15,Machine learning in nutrie...,September 2023,Oumnia Ennaji | Leonardus Vergütz | Achraf ...
16,Machine learning for weed–...,December 2023,Filbert H. Juwono | W.K. Wong | Seema Verma...
17,A systematic review of mac...,2022,Md Ekramul Hossain | Muhammad Ashad Kabir | ...
18,Examining the interplay be...,2022,Abderahman Rejeb | Karim Rejeb | Suhaiza Za...
19,A review on computer visio...,2020,Cedric Okinda | Innocent Nyalala | Tchalla ...
20,Artificial cognition for a...,2020,Misbah Pathan | Nivedita Patel | Hiteshri Y...
21,Explainable artificial int...,2022,Masahiro Ryo
22,Vision Intelligence for Sm...,March 2024,Galib Muhammad Shahriar Himel | Md. Masudul ...
23,Crop diagnostic system: A ...,December 2023,R. Abbasi | P. Martinez | R. Ahmad
24,Blockchain: A new safeguar...,2020,Jie Xu | Shuang Guo | David Xie | Yaxuan Yan